---
  - name: Ensure htpasswd is installed
    package:
      name: apache2-utils
      state: present

  - name: Create directories
    file:
      path: /root/docker/durkaproxy
      state: directory

  - name: Recreate htpasswd file in one go
    shell: |
      rm -f /root/docker/durkaproxy/htpasswd
      {% for u in http_proxy_users %}
      {% if loop.first %}
      htpasswd -cb /root/docker/durkaproxy/htpasswd {{ u.login }} {{ u.password }}
      {% else %}
      htpasswd -b  /root/docker/durkaproxy/htpasswd {{ u.login }} {{ u.password }}
      {% endif %}
      {% endfor %}
    args:
      executable: /bin/bash
